config/routes.rb
Rails.application.routes.draw do
  resources :table_referral_logs
  root 'pages#home'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/Table_Referral_logs.rb
class TableReferralLog < ApplicationRecord
    validates :recepient_email_id, presence: true , uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/table_referral_log.rb
class TableReferralLog < ApplicationRecord
    validates :recepient_email_id, presence: true , uniqueness: true
    belongs_to :user
    enum :status , [:in_queue , :email_sent , :referall_accepted , :referral_rejected]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum :role , [:native_user , :referred_user]
  has_many :table_referral_logs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/channels/application_cable/channel.rb
module ApplicationCable
  class Channel < ActionCable::Channel::Base
  end
end

app/controllers/channels/application_cable/connection.rb
module ApplicationCable
  class Connection < ActionCable::Connection::Base
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @referrals = current_user.table_referral_logs if current_user
  end
end

app/controllers/table_referral_logs_controller.rb
class TableReferralLogsController < ApplicationController
  before_action :set_table_referral_log, only: %i[ show ]
  before_action :authenticate_user!

  # GET /table_referral_logs or /table_referral_logs.json
  def index
    @table_referral_logs = current_user.table_referral_logs
  end

  # GET /table_referral_logs/1 or /table_referral_logs/1.json
  def show
    @table_referral_log = TableReferralLog.find_by(id: params[:id])
  end

  # GET /table_referral_logs/new
  def new
    @table_referral_log = TableReferralLog.new
    @table_referral_log.user_id = current_user.id
  end

  # GET /table_referral_logs/1/edit
  def edit
  end

  # POST /table_referral_logs or /table_referral_logs.json
  def create
    @table_referral_log = TableReferralLog.new(recepient_email_id: params["table_referral_log"]["recepient_email_id"], user_id: current_user.id , status: 0)
    puts "coming here"
    respond_to do |format|

      if @table_referral_log.save
        ReferralMailer.send_mail(current_user.email,params["table_referral_log"]["recepient_email_id"],@table_referral_log).deliver_later
        format.html { redirect_to table_referral_log_url(@table_referral_log), notice: "Referral was successfully created." }
        format.json { render :show, status: :created, location: @table_referral_log }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @table_referral_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /table_referral_logs/1 or /table_referral_logs/1.json
  def update
    respond_to do |format|
      if @table_referral_log.update(table_referral_log_params)
        format.html { redirect_to table_referral_log_url(@table_referral_log), notice: "Table referral log was successfully updated." }
        format.json { render :show, status: :ok, location: @table_referral_log }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @table_referral_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /table_referral_logs/1 or /table_referral_logs/1.json
  def destroy
    @table_referral_log.destroy

    respond_to do |format|
      format.html { redirect_to table_referral_logs_url, notice: "Table referral log was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_table_referral_log
      @table_referral_log = TableReferralLog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def table_referral_log_params
      params.fetch(:table_referral_log, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/table_referral_logs_helper.rb
module TableReferralLogsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Platform</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Welcome to the Referral Platform</h1>

<% if current_user %>
  <p>Welcome, <%= current_user.email %>!</p>
  <% if current_user.native_user? %>
    <p><a href = "table_referral_logs/new">Give a referral</a></p>
    <p><a href = "table_referral_logs"> View past referrals</a> </p>
  <% end %>
  <%= link_to 'Logout', destroy_user_session_path, method: :delete, data: { turbo_method: :delete } %>

<% else %>
  <%= link_to 'Login', new_user_session_path %>
  <%= link_to 'Sign up', new_user_registration_path %>
<% end %>

app/views/table_referral_logs/_form.html.erb
<%= form_with(model: table_referral_log) do |form| %>
  <% if table_referral_log.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(table_referral_log.errors.count, "error") %> prohibited this table_referral_log from being saved:</h2>

      <ul>
        <% table_referral_log.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div>
    <%= form.label :recepient_email_id, style: "display: block" %>
    <%= form.text_field :recepient_email_id %>
  </div>
<br/>

  <div>
    <p><%= form.submit %></p>
  </div>
<% end %>

app/views/table_referral_logs/_table_referral_log.html.erb
<div id="<%= dom_id table_referral_log %>">
<p><% table_referral_log.recepient_email_id %></p>
</div>

app/views/table_referral_logs/edit.html.erb
<h1>Editing table referral log</h1>

<%= render "form", table_referral_log: @table_referral_log %>

<br>

<div>
  <%= link_to "Show this table referral log", @table_referral_log %> |
  <%= link_to "Back to table referral logs", table_referral_logs_path %>
</div>

app/views/table_referral_logs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Table referral logs</h1>
<table>
  <tr>
    <th>Email</th>
    <th>Status</th>
    <th>Link</th>
  </tr>
   <% @table_referral_logs.each do |table_referral_log| %> 
    <tr>
      <td><%= table_referral_log.recepient_email_id %></td>
      <td><%= table_referral_log.status %></td>
      <td>
      <%= link_to 'show this log' ,table_referral_log %>
      </td>
    </tr>
  <% end %>
</table>

<p><a href = "/">Back to Home Page</a></p>

app/views/table_referral_logs/new.html.erb
<h1>New Referral</h1>

<%= render "form", table_referral_log: @table_referral_log %>

<br>

<div>
  <%= link_to "Back to referrals", table_referral_logs_path %>
</div>

app/views/table_referral_logs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @table_referral_log %>

<div>
  <p>recepient_email_id: <%= @table_referral_log.recepient_email_id%></p>
  <p>status of the referral: <%=@table_referral_log.status %></p>
  <p><%= link_to "Back to referrals", table_referral_logs_path %></p>
  <p><a href = "/">Back to Home Page</a></p>
</div>